Repository tc39/test262, pull requests merged in 2022-11, with the labels that each got.

#3697 Add `/iu` Unicode case folding tests
  implementation-contributed/v8/mjsunit/es6/unicode-escapes-in-regexps.js
Labels: needs review

#3713 Update Intl tests to recognize microsecond and nanosecond as sanctioned
  harness/testIntl.js
  test/intl402/NumberFormat/prototype/format/units-invalid.js
Labels: has consensus

#3730 CI: Integrate ESMeta
  .github/workflows/esmeta-test262.yml
Labels: needs review

#3676 Update expected results for CLDR 42
  test/intl402/DateTimeFormat/prototype/format/timedatestyle-en.js
  test/intl402/DateTimeFormat/prototype/formatRange/en-US.js
  test/intl402/DateTimeFormat/prototype/formatRange/fractionalSecondDigits.js
  test/intl402/DateTimeFormat/prototype/formatRangeToParts/en-US.js
  test/intl402/DateTimeFormat/prototype/formatRangeToParts/fractionalSecondDigits.js
Labels: awaiting specification

#3718 Temporal: Test throwing on time-zone-to-calendar conversion and vice versa
  test/built-ins/Temporal/Calendar/from/calendar-wrong-type.js
  test/built-ins/Temporal/Calendar/prototype/dateUntil/argument-propertybag-calendar-wrong-type.js
  test/built-ins/Temporal/Duration/compare/relativeto-propertybag-timezone-wrong-type.js
  test/built-ins/Temporal/Duration/prototype/add/relativeto-propertybag-calendar-wrong-type.js
  test/built-ins/Temporal/Duration/prototype/add/relativeto-propertybag-timezone-wrong-type.js
  test/built-ins/Temporal/Duration/prototype/round/relativeto-propertybag-calendar-wrong-type.js
  test/built-ins/Temporal/Duration/prototype/round/relativeto-propertybag-timezone-wrong-type.js
  test/built-ins/Temporal/Duration/prototype/subtract/relativeto-propertybag-calendar-wrong-type.js
  test/built-ins/Temporal/Duration/prototype/subtract/relativeto-propertybag-timezone-wrong-type.js
  test/built-ins/Temporal/Duration/prototype/total/relativeto-propertybag-calendar-wrong-type.js
  test/built-ins/Temporal/Duration/prototype/total/relativeto-propertybag-timezone-wrong-type.js
  test/built-ins/Temporal/Instant/prototype/toString/timezone-wrong-type.js
  test/built-ins/Temporal/Instant/prototype/toZonedDateTime/calendar-wrong-type.js
  test/built-ins/Temporal/Instant/prototype/toZonedDateTime/timezone-wrong-type.js
  test/built-ins/Temporal/Instant/prototype/toZonedDateTimeISO/timezone-wrong-type.js
  test/built-ins/Temporal/Now/plainDate/calendar-wrong-type.js
  test/built-ins/Temporal/Now/plainDate/timezone-wrong-type.js
  test/built-ins/Temporal/Now/plainDateISO/timezone-wrong-type.js
  test/built-ins/Temporal/Now/plainDateTime/calendar-wrong-type.js
  test/built-ins/Temporal/Now/plainDateTime/timezone-wrong-type.js
  test/built-ins/Temporal/Now/plainDateTimeISO/timezone-wrong-type.js
  test/built-ins/Temporal/Now/plainTimeISO/timezone-wrong-type.js
  test/built-ins/Temporal/Now/zonedDateTime/calendar-wrong-type.js
  test/built-ins/Temporal/Now/zonedDateTime/timezone-wrong-type.js
  test/built-ins/Temporal/Now/zonedDateTimeISO/timezone-wrong-type.js
  test/built-ins/Temporal/PlainDate/compare/argument-propertybag-calendar-wrong-type.js
  test/built-ins/Temporal/PlainDate/prototype/toZonedDateTime/timezone-wrong-type.js
  test/built-ins/Temporal/PlainDate/prototype/withCalendar/calendar-wrong-type.js
  test/built-ins/Temporal/PlainDateTime/compare/argument-propertybag-calendar-wrong-type.js
  test/built-ins/Temporal/PlainDateTime/prototype/toZonedDateTime/timezone-wrong-type.js
  test/built-ins/Temporal/PlainDateTime/prototype/withCalendar/calendar-wrong-type.js
  test/built-ins/Temporal/PlainTime/prototype/toZonedDateTime/timezone-wrong-type.js
  test/built-ins/Temporal/PlainYearMonth/compare/argument-propertybag-calendar-wrong-type.js
  test/built-ins/Temporal/TimeZone/from/timezone-wrong-type.js
  test/built-ins/Temporal/TimeZone/prototype/getPlainDateTimeFor/calendar-wrong-type.js
  test/built-ins/Temporal/ZonedDateTime/compare/argument-propertybag-calendar-wrong-type.js
  test/built-ins/Temporal/ZonedDateTime/compare/argument-propertybag-timezone-wrong-type.js
  test/built-ins/Temporal/ZonedDateTime/from/argument-propertybag-timezone-wrong-type.js
  test/built-ins/Temporal/ZonedDateTime/prototype/equals/argument-propertybag-timezone-wrong-type.js
  test/built-ins/Temporal/ZonedDateTime/prototype/since/argument-propertybag-timezone-wrong-type.js
  test/built-ins/Temporal/ZonedDateTime/prototype/until/argument-propertybag-timezone-wrong-type.js
  test/built-ins/Temporal/ZonedDateTime/prototype/withCalendar/calendar-wrong-type.js
  test/built-ins/Temporal/ZonedDateTime/prototype/withTimeZone/timezone-wrong-type.js
Labels: needs review, has consensus

#3696 Temporal: Add tests for new yearOfWeek API
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-calendar-datefromfields-called-with-null-prototype-fields.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-calendar-fields-undefined.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-leap-second.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-number.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-propertybag-calendar-instance-does-not-get-calendar-property.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-propertybag-calendar-leap-second.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-propertybag-calendar-number.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-propertybag-calendar-string.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-propertybag-calendar-wrong-type.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-propertybag-calendar-year-zero.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string-calendar-annotation.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string-critical-unknown-annotation.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string-invalid.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string-multiple-time-zone.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string-time-separators.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string-time-zone-annotation.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string-unknown-annotation.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string-with-utc-designator.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-string.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-wrong-type.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-zoneddatetime-convert.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-zoneddatetime-slots.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-zoneddatetime-timezone-getoffsetnanosecondsfor-non-integer.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-zoneddatetime-timezone-getoffsetnanosecondsfor-not-callable.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-zoneddatetime-timezone-getoffsetnanosecondsfor-out-of-range.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/argument-zoneddatetime-timezone-getoffsetnanosecondsfor-wrong-type.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/basic.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/branding.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/builtin.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/calendar-datefromfields-called-with-options-undefined.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/calendar-fields-iterable.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/calendar-temporal-object.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/cross-year.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/infinity-throws-rangeerror.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/length.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/name.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/not-a-constructor.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/prop-desc.js
  test/built-ins/Temporal/Calendar/prototype/yearOfWeek/year-zero.js
  test/built-ins/Temporal/PlainDate/prototype/yearOfWeek/basic.js
  test/built-ins/Temporal/PlainDate/prototype/yearOfWeek/branding.js
  test/built-ins/Temporal/PlainDate/prototype/yearOfWeek/custom.js
  test/built-ins/Temporal/PlainDate/prototype/yearOfWeek/prop-desc.js
  test/built-ins/Temporal/PlainDate/prototype/yearOfWeek/validate-calendar-value.js
  test/built-ins/Temporal/PlainDateTime/prototype/yearOfWeek/basic.js
  test/built-ins/Temporal/PlainDateTime/prototype/yearOfWeek/branding.js
  test/built-ins/Temporal/PlainDateTime/prototype/yearOfWeek/custom.js
  test/built-ins/Temporal/PlainDateTime/prototype/yearOfWeek/prop-desc.js
  test/built-ins/Temporal/PlainDateTime/prototype/yearOfWeek/validate-calendar-value.js
  test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/branding.js
  test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/custom.js
  test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/prop-desc.js
  test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/timezone-getoffsetnanosecondsfor-non-integer.js
  test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/timezone-getoffsetnanosecondsfor-not-callable.js
  test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/timezone-getoffsetnanosecondsfor-out-of-range.js
  test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/timezone-getoffsetnanosecondsfor-wrong-type.js
  test/built-ins/Temporal/ZonedDateTime/prototype/yearOfWeek/validate-calendar-value.js
  test/intl402/Temporal/Calendar/prototype/yearOfWeek/infinity-throws-rangeerror.js
Labels: needs review, has consensus
