Repository tc39/test262, pull requests merged in 2023-02, with the labels that each got.

#3722 Update DateTimeFormat proleptic Gregorian testing to include era
  test/intl402/DateTimeFormat/prototype/format/proleptic-gregorian-calendar.js
Labels: awaiting consensus

#3769 Temporal: Adjustments to order-of-operations tests
  test/built-ins/Temporal/PlainDate/prototype/with/order-of-operations.js
  test/built-ins/Temporal/PlainDateTime/prototype/with/order-of-operations.js
  test/built-ins/Temporal/PlainMonthDay/prototype/with/order-of-operations.js
  test/built-ins/Temporal/PlainTime/prototype/with/order-of-operations.js
  test/built-ins/Temporal/PlainYearMonth/prototype/since/order-of-operations.js
  test/built-ins/Temporal/PlainYearMonth/prototype/until/order-of-operations.js
  test/built-ins/Temporal/PlainYearMonth/prototype/with/order-of-operations.js
  test/built-ins/Temporal/ZonedDateTime/prototype/with/copies-merge-fields-object.js
  test/built-ins/Temporal/ZonedDateTime/prototype/with/order-of-operations.js
Labels: needs review, awaiting consensus

#3770 Temporal: Tests for upper limit on rounding increments
  test/built-ins/Temporal/Duration/prototype/round/roundingincrement-non-integer.js
  test/built-ins/Temporal/Duration/prototype/round/roundingincrement-out-of-range.js
  test/built-ins/Temporal/Instant/prototype/round/roundingincrement-non-integer.js
  test/built-ins/Temporal/Instant/prototype/round/roundingincrement-out-of-range.js
  test/built-ins/Temporal/Instant/prototype/since/roundingincrement-non-integer.js
  test/built-ins/Temporal/Instant/prototype/since/roundingincrement-out-of-range.js
  test/built-ins/Temporal/Instant/prototype/until/roundingincrement-non-integer.js
  test/built-ins/Temporal/Instant/prototype/until/roundingincrement-out-of-range.js
  test/built-ins/Temporal/PlainDate/prototype/since/roundingincrement-non-integer.js
  test/built-ins/Temporal/PlainDate/prototype/since/roundingincrement-out-of-range.js
  test/built-ins/Temporal/PlainDate/prototype/until/roundingincrement-non-integer.js
  test/built-ins/Temporal/PlainDate/prototype/until/roundingincrement-out-of-range.js
  test/built-ins/Temporal/PlainDateTime/prototype/round/roundingincrement-non-integer.js
  test/built-ins/Temporal/PlainDateTime/prototype/round/roundingincrement-out-of-range.js
  test/built-ins/Temporal/PlainDateTime/prototype/since/roundingincrement-non-integer.js
  test/built-ins/Temporal/PlainDateTime/prototype/since/roundingincrement-out-of-range.js
  test/built-ins/Temporal/PlainDateTime/prototype/until/roundingincrement-non-integer.js
  test/built-ins/Temporal/PlainDateTime/prototype/until/roundingincrement-out-of-range.js
  test/built-ins/Temporal/PlainTime/prototype/round/roundingincrement-non-integer.js
  test/built-ins/Temporal/PlainTime/prototype/round/roundingincrement-out-of-range.js
  test/built-ins/Temporal/PlainTime/prototype/since/roundingincrement-non-integer.js
  test/built-ins/Temporal/PlainTime/prototype/since/roundingincrement-out-of-range.js
  test/built-ins/Temporal/PlainTime/prototype/until/roundingincrement-non-integer.js
  test/built-ins/Temporal/PlainTime/prototype/until/roundingincrement-out-of-range.js
  test/built-ins/Temporal/PlainYearMonth/prototype/since/roundingincrement-non-integer.js
  test/built-ins/Temporal/PlainYearMonth/prototype/since/roundingincrement-out-of-range.js
  test/built-ins/Temporal/PlainYearMonth/prototype/until/roundingincrement-non-integer.js
  test/built-ins/Temporal/PlainYearMonth/prototype/until/roundingincrement-out-of-range.js
  test/built-ins/Temporal/ZonedDateTime/prototype/round/roundingincrement-non-integer.js
  test/built-ins/Temporal/ZonedDateTime/prototype/round/roundingincrement-out-of-range.js
  test/built-ins/Temporal/ZonedDateTime/prototype/since/roundingincrement-non-integer.js
  test/built-ins/Temporal/ZonedDateTime/prototype/since/roundingincrement-out-of-range.js
  test/built-ins/Temporal/ZonedDateTime/prototype/until/roundingincrement-non-integer.js
  test/built-ins/Temporal/ZonedDateTime/prototype/until/roundingincrement-out-of-range.js
  test/staging/Temporal/Instant/old/round.js
Labels: has consensus

#3777 Swap call order of NumberFormat's notation and roundingIncrement options
  test/intl402/NumberFormat/constructor-roundingIncrement.js
Labels: needs review

#3766 Add test to approximately format
  test/intl402/NumberFormat/prototype/formatRangeToParts/en-US.js
Labels: ECMA-402

#3771 Coverage DurationFormat formatToParts
  test/intl402/DurationFormat/prototype/formatToParts/formatToParts-styles-en.js
  test/intl402/DurationFormat/prototype/formatToParts/invalid-arguments-throws.js
Labels: awaiting author, ECMA-402

#3781 Temporal: Test copying options object in since() and until()
  test/built-ins/Temporal/Instant/prototype/since/order-of-operations.js
  test/built-ins/Temporal/Instant/prototype/until/order-of-operations.js
  test/built-ins/Temporal/PlainDate/prototype/since/order-of-operations.js
  test/built-ins/Temporal/PlainDate/prototype/until/order-of-operations.js
  test/built-ins/Temporal/PlainDateTime/prototype/since/order-of-operations.js
  test/built-ins/Temporal/PlainDateTime/prototype/until/order-of-operations.js
  test/built-ins/Temporal/PlainTime/prototype/since/order-of-operations.js
  test/built-ins/Temporal/PlainTime/prototype/until/order-of-operations.js
  test/built-ins/Temporal/PlainYearMonth/prototype/since/order-of-operations.js
  test/built-ins/Temporal/PlainYearMonth/prototype/until/order-of-operations.js
  test/built-ins/Temporal/ZonedDateTime/prototype/since/order-of-operations.js
  test/built-ins/Temporal/ZonedDateTime/prototype/until/order-of-operations.js
Labels: has consensus

#3778 Temporal: Tests for calendar-specific mergeFields
  test/built-ins/Temporal/Calendar/prototype/mergeFields/arguments-not-object.js
  test/built-ins/Temporal/Calendar/prototype/mergeFields/order-of-operations.js
  test/intl402/Temporal/Calendar/prototype/mergeFields/gregorian-mutually-exclusive-fields.js
  test/intl402/Temporal/Calendar/prototype/mergeFields/japanese-mutually-exclusive-fields.js
  test/intl402/Temporal/PlainDate/prototype/with/cross-era-boundary.js
  test/staging/Intl402/Temporal/old/japanese-era.js
Labels: has consensus

#3784 Temporal: Tests for reference ISO dates
  test/built-ins/Temporal/Calendar/prototype/monthDayFromFields/reference-year-1972.js
  test/built-ins/Temporal/Calendar/prototype/yearMonthFromFields/reference-day.js
  test/intl402/Temporal/Calendar/prototype/monthDayFromFields/reference-year-1972.js
  test/intl402/Temporal/Calendar/prototype/yearMonthFromFields/reference-day.js
  test/staging/Intl402/Temporal/old/hebrew-leap-months.js
Labels: needs review
