Repository tc39/test262, pull requests merged in 2023-11, with the labels that each got.

#3947 Update case folding tests for Unicode 15.1
  test/built-ins/RegExp/unicode_full_case_folding.js
Labels: awaiting specification

#3946 Update likely subtags tests for CLDR 44
  test/intl402/Locale/likely-subtags.js
  test/intl402/Locale/prototype/minimize/removing-likely-subtags-first-adds-likely-subtags.js
Labels: awaiting specification

#3924 Add test for firstDayOfWeek in LocaleInfo PR 70
  test/intl402/Locale/constructor-options-firstDayOfWeek-invalid.js
  test/intl402/Locale/constructor-options-firstDayOfWeek-valid.js
  test/intl402/Locale/prototype/firstDayOfWeek/branding.js
  test/intl402/Locale/prototype/firstDayOfWeek/name.js
  test/intl402/Locale/prototype/firstDayOfWeek/prop-desc.js
  test/intl402/Locale/prototype/firstDayOfWeek/valid-id.js
  test/intl402/Locale/prototype/firstDayOfWeek/valid-options.js
  test/intl402/Locale/prototype/getWeekInfo/firstDay-by-id.js
  test/intl402/Locale/prototype/getWeekInfo/firstDay-by-option.js
Labels: has consensus

#3816 Set union tests
  features.txt
  test/built-ins/Set/prototype/union/add-not-called.js
  test/built-ins/Set/prototype/union/allows-set-like-class.js
  test/built-ins/Set/prototype/union/allows-set-like-object.js
  test/built-ins/Set/prototype/union/appends-new-values.js
  test/built-ins/Set/prototype/union/array-throws.js
  test/built-ins/Set/prototype/union/builtins.js
  test/built-ins/Set/prototype/union/called-with-object.js
  test/built-ins/Set/prototype/union/combines-Map.js
  test/built-ins/Set/prototype/union/combines-empty-sets.js
  test/built-ins/Set/prototype/union/combines-itself.js
  test/built-ins/Set/prototype/union/combines-same-sets.js
  test/built-ins/Set/prototype/union/combines-sets.js
  test/built-ins/Set/prototype/union/converts-negative-zero.js
  test/built-ins/Set/prototype/union/has-is-callable.js
  test/built-ins/Set/prototype/union/keys-is-callable.js
  test/built-ins/Set/prototype/union/length.js
  test/built-ins/Set/prototype/union/name.js
  test/built-ins/Set/prototype/union/not-a-constructor.js
  test/built-ins/Set/prototype/union/receiver-not-set.js
  test/built-ins/Set/prototype/union/require-internal-slot.js
  test/built-ins/Set/prototype/union/set-like-array.js
  test/built-ins/Set/prototype/union/set-like-class-mutation.js
  test/built-ins/Set/prototype/union/set-like-class-order.js
  test/built-ins/Set/prototype/union/size-is-a-number.js
  test/built-ins/Set/prototype/union/subclass-receiver-methods.js
  test/built-ins/Set/prototype/union/subclass-symbol-species.js
  test/built-ins/Set/prototype/union/subclass.js
  test/built-ins/Set/prototype/union/union-properties.js
Labels: awaiting author
