Repository tc39/test262, pull requests merged in 2024-10, with the labels that each got.

#4241 Add basic u flag tests in v flag tests.
  test/built-ins/RegExp/prototype/exec/regexp-builtin-exec-v-flag.js
  test/built-ins/RegExp/prototype/exec/regexp-builtin-exec-v-u-flag.js
  test/built-ins/String/prototype/match/regexp-prototype-match-v-flag.js
  test/built-ins/String/prototype/match/regexp-prototype-match-v-u-flag.js
  test/built-ins/String/prototype/matchAll/regexp-prototype-matchAll-v-flag.js
  test/built-ins/String/prototype/matchAll/regexp-prototype-matchAll-v-u-flag.js
  test/built-ins/String/prototype/replace/regexp-prototype-replace-v-u-flag.js
  test/built-ins/String/prototype/search/regexp-prototype-search-v-u-flag.js.js
Labels: awaiting author

#3931 Increase coverage of String.prototype.replace $xy replacement patterns
  test/built-ins/String/prototype/replace/regexp-capture-by-index.js
Labels: needs follow-up

#4246 Update time zone mapping for CLDR46 / tzdata 2024b
  test/intl402/Intl/getCanonicalLocales/unicode-ext-canonicalize-timezone.js
Labels: needs follow-up

#4262 test(top-level-await): move out of staging module graphs hanging
  test/language/module-code/top-level-await/module-graphs-does-not-hang.js
  test/language/module-code/top-level-await/module-graphs-grandparent-tla_FIXTURE.js
  test/language/module-code/top-level-await/module-graphs-parent-tla_FIXTURE.js
  test/language/module-code/top-level-await/tla_FIXTURE.js
Labels: needs review

#4268 DurationFormat: Add tests for durations with large hour/minute/second unit values while using digital style
  test/intl402/DurationFormat/prototype/format/style-digital-large-hms-values.js
Labels: needs review
