Repository tc39/test262, pull requests merged in 2024-09, with the labels that each got.

#4152 Temporal: Tests for disallowed corner case in rounding durations
  test/built-ins/Temporal/Duration/prototype/round/round-and-balance-calendar-units-with-increment-disallowed.js
Labels: has consensus

#4158 Temporal: Tests for corner case in TZDB involving DST transition in 1919
  test/intl402/Temporal/PlainDate/prototype/toZonedDateTime/dst-skipped-cross-midnight.js
  test/intl402/Temporal/ZonedDateTime/from/dst-skipped-cross-midnight.js
  test/intl402/Temporal/ZonedDateTime/prototype/hoursInDay/dst-skipped-cross-midnight.js
  test/intl402/Temporal/ZonedDateTime/prototype/round/dst-skipped-cross-midnight.js
  test/intl402/Temporal/ZonedDateTime/prototype/startOfDay/dst-skipped-cross-midnight.js
  test/intl402/Temporal/ZonedDateTime/prototype/withPlainTime/dst-skipped-cross-midnight.js
Labels: has consensus

#4214 Add tests for `%WrapForValidIteratorPrototype%.return()` from Iterator Helpers Proposal
  test/built-ins/Iterator/from/get-return-method-when-call-return.js
  test/built-ins/Iterator/from/return-method-calls-base-return-method.js
  test/built-ins/Iterator/from/return-method-returns-iterator-result.js
  test/built-ins/Iterator/from/return-method-throws-for-invalid-this.js
Labels: awaiting author

#4213 Add more tests for v flag
  test/built-ins/RegExp/prototype/exec/regexp-builtin-exec-v-flag.js
  test/built-ins/String/prototype/match/regexp-prototype-match-v-flag.js
  test/built-ins/String/prototype/matchAll/regexp-prototype-matchAll-v-flag.js
  test/built-ins/String/prototype/replace/regexp-prototype-replace-v-flag.js
  test/built-ins/String/prototype/search/regexp-prototype-search-v-flag.js.js
Labels: awaiting author

#3729 add a test for Generator
  test/built-ins/GeneratorPrototype/return/try-finally-set-property-within-try.js
Labels: needs review
