Repository tc39/test262, pull requests merged in 2024-01, with the labels that each got.

#3974 Array length: add test ensuring RangeError is thrown
  test/built-ins/Array/length/define-own-prop-length-error.js
Labels: coverage

#3849 add Float16Array to all generic TypedArray tests
  harness/testTypedArray.js
  test/built-ins/Array/prototype/concat/Array.prototype.concat_large-typed-array.js
  test/built-ins/Array/prototype/concat/Array.prototype.concat_small-typed-array.js
  test/built-ins/Atomics/add/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/add/validate-arraytype-before-value-coercion.js
  test/built-ins/Atomics/and/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/and/validate-arraytype-before-value-coercion.js
  test/built-ins/Atomics/compareExchange/validate-arraytype-before-expectedValue-coercion.js
  test/built-ins/Atomics/compareExchange/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/compareExchange/validate-arraytype-before-replacementValue-coercion.js
  test/built-ins/Atomics/exchange/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/exchange/validate-arraytype-before-value-coercion.js
  test/built-ins/Atomics/load/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/notify/non-int32-typedarray-throws.js
  test/built-ins/Atomics/notify/validate-arraytype-before-count-coercion.js
  test/built-ins/Atomics/notify/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/or/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/or/validate-arraytype-before-value-coercion.js
  test/built-ins/Atomics/store/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/store/validate-arraytype-before-value-coercion.js
  test/built-ins/Atomics/sub/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/sub/validate-arraytype-before-value-coercion.js
  test/built-ins/Atomics/wait/non-int32-typedarray-throws.js
  test/built-ins/Atomics/wait/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/wait/validate-arraytype-before-timeout-coercion.js
  test/built-ins/Atomics/wait/validate-arraytype-before-value-coercion.js
  test/built-ins/Atomics/waitAsync/non-int32-typedarray-throws.js
  test/built-ins/Atomics/waitAsync/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/waitAsync/validate-arraytype-before-value-coercion.js
  test/built-ins/Atomics/xor/validate-arraytype-before-index-coercion.js
  test/built-ins/Atomics/xor/validate-arraytype-before-value-coercion.js
  test/built-ins/ShadowRealm/prototype/evaluate/globalthis-available-properties.js
  test/built-ins/TypedArray/prototype/copyWithin/bit-precision.js
  test/built-ins/TypedArray/prototype/fill/fill-values-conversion-operations-consistent-nan.js
  test/built-ins/TypedArray/prototype/filter/callbackfn-resize.js
  test/built-ins/TypedArray/prototype/includes/samevaluezero.js
  test/built-ins/TypedArray/prototype/map/callbackfn-resize.js
  test/built-ins/TypedArray/prototype/map/return-new-typedarray-conversion-operation-consistent-nan.js
  test/built-ins/TypedArray/prototype/set/bit-precision.js
  test/built-ins/TypedArray/prototype/set/typedarray-arg-set-values-diff-buffer-other-type-conversions-sab.js
  test/built-ins/TypedArray/prototype/set/typedarray-arg-set-values-same-buffer-other-type.js
  test/built-ins/TypedArray/prototype/slice/bit-precision.js
  test/built-ins/TypedArray/prototype/sort/sorted-values-nan.js
  test/built-ins/TypedArray/prototype/sort/sorted-values.js
  test/built-ins/TypedArrayConstructors/ctors/buffer-arg/bufferbyteoffset-throws-from-modulo-element-size-sab.js
  test/built-ins/TypedArrayConstructors/ctors/buffer-arg/bufferbyteoffset-throws-from-modulo-element-size.js
  test/built-ins/TypedArrayConstructors/ctors/buffer-arg/byteoffset-throws-from-modulo-element-size-sab.js
  test/built-ins/TypedArrayConstructors/ctors/buffer-arg/byteoffset-throws-from-modulo-element-size.js
  test/built-ins/TypedArrayConstructors/ctors/object-arg/conversion-operation-consistent-nan.js
  test/built-ins/TypedArrayConstructors/ctors/object-arg/returns.js
  test/built-ins/TypedArrayConstructors/from/nan-conversion.js
  test/built-ins/TypedArrayConstructors/from/new-instance-from-ordinary-object.js
  test/built-ins/TypedArrayConstructors/from/new-instance-from-sparse-array.js
  test/built-ins/TypedArrayConstructors/from/new-instance-from-zero.js
  test/built-ins/TypedArrayConstructors/internals/DefineOwnProperty/conversion-operation-consistent-nan.js
  test/built-ins/TypedArrayConstructors/internals/Set/conversion-operation-consistent-nan.js
  test/built-ins/TypedArrayConstructors/of/nan-conversion.js
  test/built-ins/TypedArrayConstructors/of/new-instance-from-zero.js
  test/language/statements/class/subclass/builtin-objects/TypedArray/regular-subclassing.js
  test/language/statements/class/subclass/builtin-objects/TypedArray/super-must-be-called.js
Labels: awaiting author

#3991 Temporal assertion message formatting
  harness/temporalHelpers.js
Labels: needs review

#3976 Async-from-sync test the iterator closes when .throw() is undefined
  test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-null.js
  test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined-get-return-undefined.js
  test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined-poisoned-return.js
  test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined-return-not-object.js
  test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined-return-object.js
  test/built-ins/AsyncFromSyncIteratorPrototype/throw/throw-undefined.js
Labels: has consensus
