Repository tc39/test262, pull requests merged in 2025-02, with the labels that each got.

#4350 add tests for "iterator helpers close receiver on argument validation failure"
  test/built-ins/Iterator/prototype/drop/argument-validation-failure-closes-underlying.js
  test/built-ins/Iterator/prototype/every/argument-validation-failure-closes-underlying.js
  test/built-ins/Iterator/prototype/filter/argument-validation-failure-closes-underlying.js
  test/built-ins/Iterator/prototype/find/argument-validation-failure-closes-underlying.js
  test/built-ins/Iterator/prototype/flatMap/argument-validation-failure-closes-underlying.js
  test/built-ins/Iterator/prototype/forEach/argument-validation-failure-closes-underlying.js
  test/built-ins/Iterator/prototype/map/argument-validation-failure-closes-underlying.js
  test/built-ins/Iterator/prototype/reduce/argument-validation-failure-closes-underlying.js
  test/built-ins/Iterator/prototype/reduce/non-callable-reducer.js
  test/built-ins/Iterator/prototype/some/argument-validation-failure-closes-underlying.js
  test/built-ins/Iterator/prototype/take/argument-validation-failure-closes-underlying.js
Labels: awaiting author

#4208 Add test for useGrouping off in digital style of DurationFormat
  test/intl402/DurationFormat/prototype/format/style-digital-largenumber-en.js
Labels: awaiting consensus

#4394 Add `Intl.Locale` test for `language` getter where language subtag is "und"
  test/intl402/Locale/getters.js
Labels: needs follow-up

#4345 Remove SM staging tests wrongly testing invalid LHS
  test/staging/sm/extensions/inc-dec-functioncall.js
  test/staging/sm/regress/regress-609617.js
  test/staging/sm/statements/for-of-iterator-close.js
Labels: needs follow-up

#4194 Remove source phase resolution time negative error types
  test/language/module-code/source-phase-import/import-source-binding-name-2.js
  test/language/module-code/source-phase-import/import-source-binding-name-2_FIXTURE.js
  test/language/module-code/source-phase-import/import-source-binding-name.js
  test/language/module-code/source-phase-import/import-source-binding-name_FIXTURE.js
  test/language/module-code/source-phase-import/import-source-newlines.js
  test/language/module-code/source-phase-import/import-source-newlines_FIXTURE.js
  test/language/module-code/source-phase-import/import-source.js
Labels: needs review
